# Sections content configuration file
## 
### use navigation.yml file to re-order, delete or add section of each card
### here you can find all content in all pre-build sections

### About [ about ]
about:
  image: "assets/img/man2.jpg"
  text: "<p>Hello! I’m Gilbert I. Guzman. I'm an Aspiring Cyber Security Analyst from the United States, located in El Paso, TX. My experience is in coding & ethical hacking but I also enjoy working on games & UI Design. I would love to talk to you about computers!</p>"
  list:
    - label: "Age"
      value: "23"

    - label: "Residence"
      value: "USA"

    - label: "Student/Freelance"
      value: "Currently Enrolled"

    - label: "Location"
      value: "El Paso"

    - label: "Phone"
      value: "+1 (915) 202-4744"

    - label: "E-mail"
      value: "azaze7.github@gmail.com"

  download:
    text: "Download Resume"
    link: "https://drive.google.com/"

### Services [ services ]
services:
  title: "Skills"
  items:
    - icon: "fas fa-solid fa-layer-group"
      name: "Full-Stack Development"
      text: "Moderate experience in both Back-End & Front-End development, across a multitude of programming languages."

    - icon: "fas fa-code"
      name: "Networking & Security"
      text: "Knowledgeable in TCP/IP & DNS. Moderate experience in Analyzing DDoS atacks & Penetration Testing of offensive networks."
      
    - icon: "fas fa-solid fa-robot"
      name: "Machine Learning & AI"
      text: "Basic experience using Python libraries such as TensorFlow to train datasets using Machine Learning."

    - icon: "fas fa-solid fa-bug"
      name: "Cybersecurity Tools & Reverse Engineering"
      text: "Experienced in using reverse engineering tools, such as Ghidra, IDA Pro, DShell, Metasploit, and more."

    - icon: "fas fa-solid fa-server"
      name: "Database Management"
      text: "Moderate skills in using MySQL and Microsoft SQL Server Suites for database management."

    - icon: "fas fa-wrench"
      name: "Problem Solving"
      text: "Strong analytical & troubleshooting skills. Experienced in writing & optimizing solutions."
      
    - icon: "fas fa-mobile-alt"
      name: "UI/UX Concepting"
      text: "Basic skills in creation of eye-popping yet user friendly user interfaces for webpages, apps, and games."
      
    - icon: "fas fa-camera"
      name: "Photography"
      text: "Basic experience shooting pictures and videos, can assist in creating visually stunning photos."

### Resume [ resume ]
resume:
  experience:
    title: "Work Experience"
    items:
      - year: "2019 - Present"
        name: "Student"
        text: "Enrolled Full-time as a student."
        
  education:
    title: "Education"
    items:
      - year: "2019 - Present"
        name: "The University of Texas at El Paso"
        text: "Bachelor's Degree in Computer Science with a Concentration in Secure Cyber Systems. [Current GPA: 3.22]"

      - year: "2015 - 2018"
        name: "El Paso Community College"
        text: "Associate of Arts Degree. [GPA: 3.24]"

      - year: "2015 - 2019"
        name: "Mission Early College High School"
        text: "High School Diploma. [GPA: 3.77]"

### Skills [ skills ]
skills:
  columns:
    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Design Skills"
      items:
        - label: "Coding Comments"
          value: "85" #0-100 progress in %

        - label: "Microsoft Office"
          value: "80" #0-100 progress in %

        - label: "Web Design"
          value: "75" #0-100 progress in %

        - label: "Adobe Creative Cloud"
          value: "70" #0-100 progress in %

    - type: "dotted" #skills progress type - default, dotted, circles, list
      title: "Languages Skills"
      items:
        - label: "English"
          value: "95" #0-100 progress in %

        - label: "Spanish"
          value: "65" #0-100 progress in %

    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "Coding Skills"
      items:
        - label: "Python"
          value: "95" #0-100 progress in %

        - label: "Java"
          value: "90" #0-100 progress in %

        - label: "C / C++ / C#"
          value: "85" #0-100 progress in %
          
        - label: "Markdown"
          value: "80" #0-100 progress in %

        - label: "HTML / JavaScript / CSS3"
          value: "75"

        - label: "RISC-V Assembly"
          value: "70" #0-100 progress in %
          
        - label: "PHP / MySQL"
          value: "70"

    - type: "list" #skills progress type - default, dotted, circles, list
      title: "Knowledge"
      items:
        - label: "Machine Virtualization"
          value: "" #0-100 progress in %

        - label: "TCP/IP Allocation and Monitoring"
          value: "" #0-100 progress in %

        - label: "iOS, Andriod, Windows, & Linux"
          value: "" #0-100 progress in %

        - label: "Photo Editing via Adobe Lightroom & Photoshop"
          value: "" #0-100 progress in %

        - label: "Leadership & Teamwork"
          value: "" #0-100 progress in %

        - label: "Reverse Engineering"
          value: "" #0-100 progress in %

        - label: "UI Design"
          value: "" #0-100 progress in %

        - label: "Game Design"
          value: "" #0-100 progress in %

### Facts [ facts ]
facts:
  title: "Interests"
  items:
    - icon: "fas fa-solid fa-plane-departure"
      name: "Travel"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-solid fa-ghost"
      name: "Gaming"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-solid fa-chess"
      name: "Chess"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-solid fa-book"
      name: "Reading"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
          
### Testimonials [ testimonials ]
testimonials:
  title: "Testimonials"
  items:
    - image: "assets/img/testimonials/rev1.jpg"
      name: "Helen Floyd"
      role: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      
    - image: "assets/img/testimonials/rev1.jpg"
      name: "The Joker"
      role: "Clown Super Villain"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - image: "assets/img/testimonials/rev1.jpg"
      name: "Mr. Guy"
      role: "Customer / Social Media Influencer"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

### Custom Text [ text ]
text:
  title: "Personal Projects / Course Work"
  items: 
    - url: "https://github.com/Azaze7"
      image: "assets/img/clients/client1big.png"
        
### Clients [ clients ]
clients:
  title: "Clients / Events"
  items:
    - url: "https://devcom.army.mil/"
      image: "assets/img/clients/client1big.png"

    - url: "https://www.linkedin.com/posts/bandit-game-studio_gamejam-jesseschell-gaia-activity-7051603509477052416-23Oy"
      image: "assets/img/clients/client2big.png"

### Contact Info [ contacts-info ]
contacts_info:
  title: "Contact Info"
  list:
    - label: "Phone"
      icon: "fas fa-phone"
      value: "+1 (915) 202-4744"

    - label: "Email"
      icon:  "fas fa-envelope"
      value: "<a href='mailto:giguzman@miners.utep.edu'>giguzman@miners.utep.edu</a>"

    - label: "Address"
      icon: "fas fa-map-marker-alt"
      value: "1234 University Blvd, El Paso"
    
    - label: "Freelance Available"
      icon: "fas fa-user-tie"
      value: "I am currently available for Freelance hire."

### Contact Form [ contacts-form ]
contacts_form:
  title: "Contact Form"

