# Sections content configuration file
## 
### use navigation.yml file to re-order, delete or add section of each card
### here you can find all content in all pre-build sections

### About [ about ]
about:
  image: "assets/img/man2.jpg"
  text: "<p>Hello! I’m Gilbert I. Guzman. I'm a Cyber Security Analyst from the United States, located in El Paso, TX. I have much experience in Coding & Ethical Hacking. I am also great at UI Design. I'd love to talk with you about technology!</p>"
  list:
    - label: "Age"
      value: "23"

    - label: "Residence"
      value: "USA"

    - label: "Student/Freelance"
      value: "Available"

    - label: "Location"
      value: "El Paso"

    - label: "Phone"
      value: "+1 (915) 202-4744"

    - label: "E-mail"
      value: "giguzman@miners.utep.edu"

  download:
    text: "Download Resume"
    link: "https://drive.google.com/"

### Services [ services ]
services:
  title: "Skills"
  items:
    - icon: "fas fa-code"
      name: "Full-Stack Development"
      text: "I'm fully versed in Back-End & Front-End development for any project you need."

    - icon: "fas fa-code"
      name: "Web Development"
      text: "I can create Modern and mobile-ready websites for your project or business."

    - icon: "fas fa-mobile-alt"
      name: "UI/UX Concepting"
      text: "I can assist in the creation of eye-popping yet user friendly user interfaces for both web and apps."
      
    - icon: "fas fa-gamepad"
      name: "Game Development"
      text: "I can help develop unique and memorible games for android, ios, and more."
      
    - icon: "fas fa-camera"
      name: "Photography"
      text: "I have experience in professional photography, and can assist in creating visually stunning photos for you or your social media."

### Resume [ resume ]
resume:
  experience:
    title: "Work Experience"
    items:
      - year: "2013 - Present"
        name: "Art Director - Facebook Inc"
        text: "Collaborate with creative and development teams on the execution of ideas."

      - year: "2011 - 2012"
        name: "Front-end Developer - Google Inc"
        text: "Monitored technical aspects of the front-end delivery for several projects."

      - year: "2009 - 2010"
        name: "Senior Developer - Abc Inc"
        text: "Optimize website performance using latest technology."
        
  education:
    title: "Education"
    items:
      - year: "2006 - 2008"
        name: "Art University of New York"
        text: "Bachelor's Degree in Computer Science ABC Technical Institute, Jefferson, Missouri"

      - year: "2005 - 2006"
        name: "Programming Course"
        text: "Coursework - Git, WordPress, Javascript, iOS, Android."

      - year: "2004 - 2005"
        name: "Web Design Course"
        text: "Converted Photoshop layouts to web pages using HTML, CSS, and JavaScript"

  education:
    title: "Course Work"
    items:
      - year: "2006 - 2008"
        name: "Art University of New York"
        text: "Bachelor's Degree in Computer Science ABC Technical Institute, Jefferson, Missouri"

      - year: "2005 - 2006"
        name: "Programming Course"
        text: "Coursework - Git, WordPress, Javascript, iOS, Android."

      - year: "2004 - 2005"
        name: "Web Design Course"
        text: "Converted Photoshop layouts to web pages using HTML, CSS, and JavaScript"

  education:
    title: "Personal Projects"
    items:
      - year: "2006 - 2008"
        name: "Art University of New York"
        text: "Bachelor's Degree in Computer Science ABC Technical Institute, Jefferson, Missouri"

      - year: "2005 - 2006"
        name: "Programming Course"
        text: "Coursework - Git, WordPress, Javascript, iOS, Android."

      - year: "2004 - 2005"
        name: "Web Design Course"
        text: "Converted Photoshop layouts to web pages using HTML, CSS, and JavaScript"

### Skills [ skills ]
skills:
  columns:
    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Design Skills"
      items:
        - label: "Web Design"
          value: "70" #0-100 progress in %

        - label: "Illustrations"
          value: "90" #0-100 progress in %

        - label: "Photoshop"
          value: "75" #0-100 progress in %

        - label: "Graphic Design"
          value: "80" #0-100 progress in %

    - type: "dotted" #skills progress type - default, dotted, circles, list
      title: "Languages Skills"
      items:
        - label: "English"
          value: "90" #0-100 progress in %

        - label: "German"
          value: "70" #0-100 progress in %

        - label: "Italian"
          value: "55" #0-100 progress in %

        - label: "French"
          value: "85" #0-100 progress in %

    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "Coding Skills"
      items:
        - label: "Python"
          value: "100" #0-100 progress in %

        - label: "C / C++"
          value: "95" #0-100 progress in %

        - label: "Java / JavaScript"
          value: "90" #0-100 progress in %
          
        - label: "PHP / MYSQL"
          value: "85" #0-100 progress in %

        - label: "HTML"
          value: "80" #0-100 progress in %

    - type: "list" #skills progress type - default, dotted, circles, list
      title: "Knowledge"
      items:
        - label: "Website hosting"
          value: "" #0-100 progress in %

        - label: "iOS and android apps"
          value: "" #0-100 progress in %

        - label: "Create logo design"
          value: "" #0-100 progress in %

        - label: "Design for print"
          value: "" #0-100 progress in %

        - label: "Modern and mobile-ready"
          value: "" #0-100 progress in %

        - label: "Advertising services include"
          value: "" #0-100 progress in %

        - label: "Graphics and animations"
          value: "" #0-100 progress in %

        - label: "Search engine marketing"
          value: "" #0-100 progress in %

### Facts [ facts ]
facts:
  title: "Interests"
  items:
    - icon: "fas fa-solid fa-mountain-city"
      name: "Travel"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-solid fa-joystick"
      name: "Gaming"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-chess-knight"
      name: "Chess"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-solid fa-book-open-cover"
      name: "Reading"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
          
### Testimonials [ testimonials ]
testimonials:
  title: "Testimonials"
  items:
    - image: "assets/img/testimonials/rev1.jpg"
      name: "Helen Floyd"
      role: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      
    - image: "assets/img/testimonials/rev1.jpg"
      name: "Helen Floyd"
      role: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

### Clients [ clients ]
clients:
  title: "Clients"
  items:
    - url: "https://www.google.com"
      image: "assets/img/clients/client1.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client2.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client3.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client4.png"
      
### Custom Text [ text ]
text:
  title: "Custom Text"
  text: "
        <p>
            Now there is more fashion. There is no so-called trends. Now chase after anything not necessary — nor for fashionable color nor the shape, nor for style. Think about the content that you want to invest in a created object, and only then will form. The thing is your spirit. A spirit unlike forms hard copy.
        </p>
        <p>
            Here choose yourself like that, without any looking back, do your personal, home, small fashion, and all will be well.
        </p>
        "

### Contact Info [ contacts-info ]
contacts_info:
  title: "Contacts Info"
  list:
    - label: "Phone"
      icon: "fas fa-phone"
      value: "+ (231) 456 67 89"

    - label: "Email"
      icon:  "fas fa-envelope"
      value: "<a href='mailto:steve-pearson@gmail.com'>steve-pearson@gmail.com</a>"

    - label: "Address"
      icon: "fas fa-map-marker-alt"
      value: "2621 W Pico Blvd, Los Angeles"
    
    - label: "Freelance Available"
      icon: "fas fa-user-tie"
      value: "I am available for Freelance hire"

### Contact Form [ contacts-form ]
contacts_form:
  title: "Contact Form"

