# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  logo_text: "Gilbert <strong>Guzman</strong>"
  logo_hover_text: "Download <strong>Resume</strong>"
  quick_colors: "red" # select quick color schemes: "beige", "blue", "brown", "green_light", "green", "orange", "purple", "red", "yellow_light", "yellow". If empty colors taken from _sass/ryancv/settings.scss

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "Coding Projects"
      slug: "f-content"
      
    - name: "Videos"
      slug: "f-video"

    - name: "Images"
      slug: "f-image"
